[package]
name = "simpler-conrod-example"
version = "0.1.0"
authors = ["David Ross <daboross@daboross.net>"]

[dependencies]
glium = "0.19"
glutin = "0.11"
rusttype = "0.3"
conrod = { version = "0.57", features = ["winit", "glium"] }
